name: Record
version: '1.21.1-1.0.0'
main: de.skyking_px.record.Record
api-version: '1.21'
commands:
  rec:
    description: Shows the '[Recording]' status in your Displayname
    usage: /<command>
    permission: lsrec.rec
